#pragma once

#if defined(__GNUC__) && defined(__riscv)

#define WCH_FAST_IRQ_HANDLER(name)                                  \
void name(void)                                                 \
__attribute__((interrupt("WCH-Interrupt-fast"), used, noinline, noipa))

#else
#error "WCH fast interrupt attribute requires WCH RISC-V GCC"
#endif


WCH_FAST_IRQ_HANDLER(NMI_Handler);
WCH_FAST_IRQ_HANDLER(HardFault_Handler);
WCH_FAST_IRQ_HANDLER(Ecall_M_Mode_Handler);
WCH_FAST_IRQ_HANDLER(Ecall_U_Mode_Handler);
WCH_FAST_IRQ_HANDLER(Break_Point_Handler);
WCH_FAST_IRQ_HANDLER(SysTick_Handler);
WCH_FAST_IRQ_HANDLER(SW_Handler);

/* External interrupts */
WCH_FAST_IRQ_HANDLER(WWDG_IRQHandler);
WCH_FAST_IRQ_HANDLER(PVD_IRQHandler);
WCH_FAST_IRQ_HANDLER(TAMPER_IRQHandler);
WCH_FAST_IRQ_HANDLER(RTC_IRQHandler);
WCH_FAST_IRQ_HANDLER(FLASH_IRQHandler);
WCH_FAST_IRQ_HANDLER(RCC_IRQHandler);

WCH_FAST_IRQ_HANDLER(EXTI0_IRQHandler);
WCH_FAST_IRQ_HANDLER(EXTI1_IRQHandler);
WCH_FAST_IRQ_HANDLER(EXTI2_IRQHandler);
WCH_FAST_IRQ_HANDLER(EXTI3_IRQHandler);
WCH_FAST_IRQ_HANDLER(EXTI4_IRQHandler);

WCH_FAST_IRQ_HANDLER(DMA1_Channel1_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel2_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel3_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel4_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel5_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel6_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel7_IRQHandler);

WCH_FAST_IRQ_HANDLER(ADC1_2_IRQHandler);

WCH_FAST_IRQ_HANDLER(USB_HP_CAN1_TX_IRQHandler);
WCH_FAST_IRQ_HANDLER(USB_LP_CAN1_RX0_IRQHandler);
WCH_FAST_IRQ_HANDLER(CAN1_RX1_IRQHandler);
WCH_FAST_IRQ_HANDLER(CAN1_SCE_IRQHandler);

WCH_FAST_IRQ_HANDLER(EXTI9_5_IRQHandler);

WCH_FAST_IRQ_HANDLER(TIM1_BRK_IRQHandler);
WCH_FAST_IRQ_HANDLER(TIM1_UP_IRQHandler);
WCH_FAST_IRQ_HANDLER(TIM1_TRG_COM_IRQHandler);
WCH_FAST_IRQ_HANDLER(TIM1_CC_IRQHandler);

WCH_FAST_IRQ_HANDLER(TIM2_IRQHandler);
WCH_FAST_IRQ_HANDLER(TIM3_IRQHandler);
WCH_FAST_IRQ_HANDLER(TIM4_IRQHandler);

WCH_FAST_IRQ_HANDLER(I2C1_EV_IRQHandler);
WCH_FAST_IRQ_HANDLER(I2C1_ER_IRQHandler);
WCH_FAST_IRQ_HANDLER(I2C2_EV_IRQHandler);
WCH_FAST_IRQ_HANDLER(I2C2_ER_IRQHandler);

WCH_FAST_IRQ_HANDLER(SPI1_IRQHandler);
WCH_FAST_IRQ_HANDLER(SPI2_IRQHandler);

WCH_FAST_IRQ_HANDLER(USART1_IRQHandler);
WCH_FAST_IRQ_HANDLER(USART2_IRQHandler);
WCH_FAST_IRQ_HANDLER(USART3_IRQHandler);

WCH_FAST_IRQ_HANDLER(EXTI15_10_IRQHandler);
WCH_FAST_IRQ_HANDLER(RTCAlarm_IRQHandler);
WCH_FAST_IRQ_HANDLER(USBWakeUp_IRQHandler);

WCH_FAST_IRQ_HANDLER(USBFS_IRQHandler);
WCH_FAST_IRQ_HANDLER(USBFSWakeUp_IRQHandler);

WCH_FAST_IRQ_HANDLER(UART4_IRQHandler);
WCH_FAST_IRQ_HANDLER(DMA1_Channel8_IRQHandler);