#ifndef DISPLAYER_CHIP_CONFIG_H
#define DISPLAYER_CHIP_CONFIG_H

#define DISPLAYER_CHIP_ID_ST7735S 1U
#define DISPLAYER_CHIP_ID_ST7789 2U

/*
 * 手动选择当前显示芯片。
 * 新增芯片时在下面加 ID 和对应分支，不通过构建参数传尺寸或型号。
 */
#define DISPLAYER_CHIP_SELECTED DISPLAYER_CHIP_ID_ST7789




#if (DISPLAYER_CHIP_SELECTED == DISPLAYER_CHIP_ID_ST7735S)



#define DISPLAYER_CHIP_USE_ST7735S 1U
#define DISPLAYER_CHIP_USE_ST7789  0U
/*
 * 当前 ST7735S 适配层给 Screen 暴露的终端字符网格。
 * 这里只定义字符格数量，不定义面板像素宽高。
 */
#define DISPLAYER_CHIP_TEXT_COLUMNS 16U
#define DISPLAYER_CHIP_TEXT_ROWS    20U



#elif(DISPLAYER_CHIP_SELECTED == DISPLAYER_CHIP_ID_ST7789)


#define DISPLAYER_CHIP_USE_ST7789 1U
#define DISPLAYER_CHIP_USE_ST7735S 0U
#define DISPLAYER_CHIP_TEXT_COLUMNS 30U
#define DISPLAYER_CHIP_TEXT_ROWS    40U





#else
#define DISPLAYER_CHIP_USE_ST7735S 0U
#define DISPLAYER_CHIP_USE_ST7789  0U
#error "Unsupported DISPLAYER_CHIP_SELECTED"
#endif

#endif /* DISPLAYER_CHIP_CONFIG_H */
